name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.41.0-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Install Playwright
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"  
      - name: Start Playwright
        run: |
          npm install playwright
          npx playwright --chromium=ci  
      - name: Run tests
        run: mvn -Dtest=TestAPI test
      - name: Stop Playwright
        run: |
          pkill playwright

      - name: Report test results
        run: |
          mvn test -Dtest=TestAPI -DoutputType=json > report.json
          echo "Test Results: $(cat report.json)" >> output.txt  
        env:
          HOME: /root
